version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: moodle-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./db:/var/lib/mysql

  web:
    build: .
    container_name: moodle-web
    restart: unless-stopped
    depends_on:
      - db
    network_mode: "host"
    environment:
      MOODLE_DBTYPE: mysqli
      MOODLE_DBHOST: 127.0.0.1
      MOODLE_DBNAME: moodle
      MOODLE_DBUSER: moodle
      MOODLE_DBPASS: moodle
      HOST_IP: 192.168.0.20
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
    working_dir: /var/www/html
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
