services:
  db:
    image: mysql:8.4
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  moodle:
    build: .
    container_name: moodle
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      MOODLE_URL:
      MOODLE_DBTYPE: mysqli
      MOODLE_DBHOST: db
      MOODLE_DBNAME: mydatabase
      MOODLE_DBUSER: myuser
      MOODLE_DBPASS: mypassword
      MOODLE_DIR: /var/www/html
      MOODLE_DATA: /var/www/moodledata
      WS_ADMIN_USERNAME: rgenieadmin
      WS_ADMIN_PASSWORD: RGenieAdmin@123
      WS_ADMIN_EMAIL: rgenieadmin@gmail.com
      WS_ADMIN_FIRSTNAME: RGenie
      WS_ADMIN_LASTNAME: Admin
      WS_RGENIE_ADMIN_SERVICE_SHORTNAME: rgenie_admin_service 
      WS_RGENIE_ADMIN_SERVICE_NAME: RGenie Admin Service
      WS_RGENIE_ADMIN_SERVICE_FUNCTIONS: >
        auth_email_signup_user,
        core_user_get_users_by_field,
        core_course_get_categories,
        core_course_get_courses,
        core_course_get_courses_by_field,
        core_course_get_contents
      WS_RGENIE_USER_SERVICE_SHORTNAME: rgenie_user_service
      WS_RGENIE_USER_SERVICE_NAME: RGenie User Service
      WS_RGENIE_USER_SERVICE_FUNCTIONS: >
        core_course_get_categories,
        core_course_get_courses
    ports:
      - "8000:80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata

volumes:
  db_data:

networks:
  default:
    external:
      name: moodle-net
